//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_p_image
    {
        public int status_id { get; set; }
        public string link { get; set; }
        public Nullable<int> product_id { get; set; }
    
        public virtual tb_product tb_product { get; set; }
    }
}
