//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_review
    {
        public int review_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string reviewer_name { get; set; }
        public string reviewer_email { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public int rating { get; set; }
    
        public virtual tb_product tb_product { get; set; }
    }
}
