//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class velaMaryEntities : DbContext
    {
        public velaMaryEntities()
            : base("name=velaMaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_blog> tb_blog { get; set; }
        public virtual DbSet<tb_cart> tb_cart { get; set; }
        public virtual DbSet<tb_cart_status> tb_cart_status { get; set; }
        public virtual DbSet<tb_catalog> tb_catalog { get; set; }
        public virtual DbSet<tb_collection> tb_collection { get; set; }
        public virtual DbSet<tb_product> tb_product { get; set; }
        public virtual DbSet<tb_review> tb_review { get; set; }
        public virtual DbSet<tb_role> tb_role { get; set; }
        public virtual DbSet<tb_size> tb_size { get; set; }
        public virtual DbSet<tb_tag> tb_tag { get; set; }
        public virtual DbSet<tb_u_address> tb_u_address { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
        public virtual DbSet<tb_p_image> tb_p_image { get; set; }
    }
}
