//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace velaMaryWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_product()
        {
            this.tb_review = new HashSet<tb_review>();
            this.tb_catalog = new HashSet<tb_catalog>();
        }
    
        public int product_id { get; set; }
        public string name { get; set; }
        public string details { get; set; }
        public int price { get; set; }
        public int quantity { get; set; }
        public string image { get; set; }
        public string sizechart { get; set; }
        public Nullable<int> size_id { get; set; }
        public Nullable<int> cart_id { get; set; }
        public Nullable<int> collection_id { get; set; }
    
        public virtual tb_cart tb_cart { get; set; }
        public virtual tb_collection tb_collection { get; set; }
        public virtual tb_size tb_size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_review> tb_review { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_catalog> tb_catalog { get; set; }
    }
}
